language: scala

cache:
  directories:
  - "$HOME/.cache"
install: mvn install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script: mvn test -P !build-extras -B

notifications:
  email:
    recipients:
    - chaitanyamvamsi@gmail.com
    on_success: change
    on_failure: always

after_success:
  - openssl aes-256-cbc -K $encrypted_02e7bfc60840_key -iv $encrypted_02e7bfc60840_iv -in .travis/codesigning.asc.enc -out .travis/codesigning.asc -d
  - gpg --fast-import .travis/codesigning.asc
  - mvn deploy -P sign,build-extras --settings .travis/settings.xml

